google_speech:
  base_url: "https://www.google.com/speech-api/v2/recognize"
  api_key: "AIzaSyC8_TgU0ov1unX6eBGgiD5Ej2K5pv_dqbQ"
  file_path: "data/"

voice_text:
  api_key: "v0n92m958evtkw4l"
  file_path: "data/"